ScreenManager:
    MainScreen:
    Level1:
    Level2:
    Level3:
    Level4:
    Level5:
    Level6:
    Level7:
    Level8:
    Level9:
    Level10:
    Level11:
    Level12:
    Level13:
    Level14:
    Level15:
    Level16:
    Level17:
    Level18:
    Level19:
    Level20:
    Level21:
    Level22:
    Level23:
    Level24:
    AboutUs:
    AllLevelsCompleted:

<AboutUs>:
    name: "aboutus"
    GridLayout:
        rows: 2
        canvas.before:
            Color:
                rgba: (0.6, 0.6, 0.6, 0.8)
            Rectangle:
                pos: self.pos
                size: self.size
                source: "bg_cointex.png"
        Label:
            size_hint_y: 0.9
            text_size: self.size
            font_size: 20
            halign: 'left'
            valign: 'top'
            text: "CoinTex version 1.2 is developed by Ahmed Fawzy Gad who is interested in machine learning, deep learning, computer vision, and Python. The game is completely developed in Python using the Kivy cross-platform framework.\n\nFeel free to contact me for any questions or recommendations:\nE-mail: ahmed.f.gad@gmail.com\nFacebook: https://www.facebook.com/ahmed.f.gadd\nLinkedIn: https://www.linkedin.com/in/ahmedfgad\nTowardsDataScience: https://towardsdatascience.com/@ahmedfgad \nResearchGate: https://www.researchgate.net/profile/Ahmed_Gad13"
        ImageButton:
            size_hint_y: 0.1
            source: "images/other-images/Main-Screen.png"
            on_release: app.root.current="main"

<AllLevelsCompleted>:
    name: "alllevelscompleted"
    GridLayout:
        rows: 2
        canvas.before:
            Color:
                rgba: (0.6, 0.6, 0.6, 0.8)
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/bg_cointex.png"
        Image:
            size_hint_y: 0.9
            source: "images/other-images/Congratulations-Passed.png"
        ImageButton:
            size_hint_y: 0.1
            source: "images/other-images/Main-Screen.png"
            on_release: app.root.current="main"

<MainScreen>:
    name: "main"
    on_enter: app.main_screen_on_enter()
    on_leave: app.main_screen_on_leave()
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            size_hint_y: 0.08
            ImageButton:
                source: "./images/other-images/About-Us.png"
                on_release: app.root.current="aboutus"
        GridLayout:
            id: lvls_imagebuttons
            cols: 4
            spacing: (5,5)
            size_hint_y: 0.92
            canvas.before:
                Rectangle:
                    pos: self.pos
                    size: self.size
                    source: "images/bg_cointex.png"
            ImageButton:
                source: "images/levels-images/1.png"
                on_release: app.root.current="level1"
            ImageButton:
                source: "images/levels-images/2.png"
                on_release: app.root.current="level2"
            ImageButton:
                source: "images/levels-images/3.png"
                on_release: app.root.current="level3"
            ImageButton:
                source: "images/levels-images/4.png"
                on_release: app.root.current="level4"
            ImageButton:
                source: "images/levels-images/5.png"
                on_release: app.root.current="level5"
            ImageButton:
                source: "images/levels-images/6.png"
                on_release: app.root.current="level6"
            ImageButton:
                source: "images/levels-images/7.png"
                on_release: app.root.current="level7"
            ImageButton:
                source: "images/levels-images/8.png"
                on_release: app.root.current="level8"
            ImageButton:
                source: "images/levels-images/9.png"
                on_release: app.root.current="level9"
            ImageButton:
                source: "images/levels-images/10.png"
                on_release: app.root.current="level10"
            ImageButton:
                source: "images/levels-images/11.png"
                on_release: app.root.current="level11"
            ImageButton:
                source: "images/levels-images/12.png"
                on_release: app.root.current="level12"
            ImageButton:
                source: "images/levels-images/13.png"
                on_release: app.root.current="level13"
            ImageButton:
                source: "images/levels-images/14.png"
                on_release: app.root.current="level14"
            ImageButton:
                source: "images/levels-images/15.png"
                on_release: app.root.current="level15"
            ImageButton:
                source: "images/levels-images/16.png"
                on_release: app.root.current="level16"
            ImageButton:
                source: "images/levels-images/17.png"
                on_release: app.root.current="level17"
            ImageButton:
                source: "images/levels-images/18.png"
                on_release: app.root.current="level18"
            ImageButton:
                source: "images/levels-images/19.png"
                on_release: app.root.current="level19"
            ImageButton:
                source: "images/levels-images/20.png"
                on_release: app.root.current="level20"
            ImageButton:
                source: "images/levels-images/21.png"
                on_release: app.root.current="level21"
            ImageButton:
                source: "images/levels-images/22.png"
                on_release: app.root.current="level22"
            ImageButton:
                source: "images/levels-images/23.png"
                on_release: app.root.current="level23"
            ImageButton:
                source: "images/levels-images/24.png"
                on_release: app.root.current="level24"

<Level1>:
    name: "level1"
    on_pre_enter: app.screen_on_pre_enter(1)
    on_pre_leave: app.screen_on_pre_leave(1)
    on_enter: app.screen_on_enter(1)
    FloatLayout:
        id: layout_lvl1
        on_touch_down: app.touch_down_handler(1, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl1.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl1
        LevelNumber
            id: level_number_lvl1
        RemainingLifePercent
            id: remaining_life_percent_lvl1
        Monster:
            id: monster1_image_lvl1
            monst_anim_duration_low: 3.5
            monst_anim_duration_high: 4.5
        Character:
            id: character_image_lvl1

<Level2>:
    name: "level2"
    on_pre_enter: app.screen_on_pre_enter(2)
    on_pre_leave: app.screen_on_pre_leave(2)
    on_enter: app.screen_on_enter(2)
    FloatLayout:
        id: layout_lvl2
        on_touch_down: app.touch_down_handler(2, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl2.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl2
        LevelNumber
            id: level_number_lvl2
        RemainingLifePercent
            id: remaining_life_percent_lvl2
        Monster:
            id: monster1_image_lvl2
            monst_anim_duration_low: 2.5
            monst_anim_duration_high: 3.5
        Character:
            id: character_image_lvl2

<Level3>:
    name: "level3"
    on_pre_enter: app.screen_on_pre_enter(3)
    on_pre_leave: app.screen_on_pre_leave(3)
    on_enter: app.screen_on_enter(3)
    FloatLayout:
        id: layout_lvl3
        on_touch_down: app.touch_down_handler(3, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl3.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl3
        LevelNumber
            id: level_number_lvl3
        RemainingLifePercent
            id: remaining_life_percent_lvl3
        Monster:
            id: monster1_image_lvl3
            monst_anim_duration_low: 1.0
            monst_anim_duration_high: 1.5
        Character:
            id: character_image_lvl3

<Level4>:
    name: "level4"
    on_pre_enter: app.screen_on_pre_enter(4)
    on_pre_leave: app.screen_on_pre_leave(4)
    on_enter: app.screen_on_enter(4)
    FloatLayout:
        id: layout_lvl4
        on_touch_down: app.touch_down_handler(4, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl4.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl4
        LevelNumber
            id: level_number_lvl4
        RemainingLifePercent
            id: remaining_life_percent_lvl4
        Fire:
            id: fire1_lvl4
            fire_start_pos_hint: {'x': 1.5, 'y': 0.5}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.5}
            fire_anim_duration: 2.5
        Monster:
            id: monster1_image_lvl4
            monst_anim_duration_low: 2.5
            monst_anim_duration_high: 3.5
        Character:
            id: character_image_lvl4

<Level5>:
    name: "level5"
    on_pre_enter: app.screen_on_pre_enter(5)
    on_pre_leave: app.screen_on_pre_leave(5)
    on_enter: app.screen_on_enter(5)
    FloatLayout:
        id: layout_lvl5
        on_touch_down: app.touch_down_handler(5, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl5.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl5
        LevelNumber
            id: level_number_lvl5
        RemainingLifePercent
            id: remaining_life_percent_lvl5
        Fire:
            id: fire1_lvl5
            fire_start_pos_hint: {'x': 1.5, 'y': 0.7}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.7}
            fire_anim_duration: 3.0
        Fire:
            id: fire2_lvl5
            fire_start_pos_hint: {'x': 1.5, 'y': 0.3}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.3}
            fire_anim_duration: 2.0
        Monster:
            id: monster1_image_lvl5
            monst_anim_duration_low: 1.0
            monst_anim_duration_high: 1.5
        Character:
            id: character_image_lvl5

<Level6>:
    name: "level6"
    on_pre_enter: app.screen_on_pre_enter(6)
    on_pre_leave: app.screen_on_pre_leave(6)
    on_enter: app.screen_on_enter(6)
    FloatLayout:
        id: layout_lvl6
        on_touch_down: app.touch_down_handler(6, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl6.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl6
        LevelNumber
            id: level_number_lvl6
        RemainingLifePercent
            id: remaining_life_percent_lvl6
        Fire:
            id: fire1_lvl6
            fire_start_pos_hint: {'x': 1.5, 'y': 0.8}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.8}
            fire_anim_duration: 2.5
        Fire:
            id: fire2_lvl6
            fire_start_pos_hint: {'x': 1.5, 'y': 0.2}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.2}
            fire_anim_duration: 2.0
        Fire:
            id: fire3_lvl6
            fire_start_pos_hint: {'x': 0.5, 'y': 1.5}
            fire_end_pos_hint: {'x': 0.5, 'y': -0.5}
            fire_anim_duration: 3.5
        Monster:
            id: monster1_image_lvl6
            monst_anim_duration_low: 2.5
            monst_anim_duration_high: 3.0
        Character:
            id: character_image_lvl6

<Level7>:
    name: "level7"
    on_pre_enter: app.screen_on_pre_enter(7)
    on_pre_leave: app.screen_on_pre_leave(7)
    on_enter: app.screen_on_enter(7)
    FloatLayout:
        id: layout_lvl7
        on_touch_down: app.touch_down_handler(7, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl7.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl7
        LevelNumber
            id: level_number_lvl7
        RemainingLifePercent
            id: remaining_life_percent_lvl7
        Monster:
            id: monster1_image_lvl7
            monst_anim_duration_low: 1.0
            monst_anim_duration_high: 1.5
        Monster:
            id: monster2_image_lvl7
            monst_anim_duration_low: 1.5
            monst_anim_duration_high: 2.5
        Monster:
            id: monster3_image_lvl7
            monst_anim_duration_low: 1.5
            monst_anim_duration_high: 2.5
        Character:
            id: character_image_lvl7

<Level8>:
    name: "level8"
    on_pre_enter: app.screen_on_pre_enter(8)
    on_pre_leave: app.screen_on_pre_leave(8)
    on_enter: app.screen_on_enter(8)
    FloatLayout:
        id: layout_lvl8
        on_touch_down: app.touch_down_handler(8, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl8.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl8
        LevelNumber
            id: level_number_lvl8
        RemainingLifePercent
            id: remaining_life_percent_lvl8
        Monster:
            id: monster1_image_lvl8
            monst_anim_duration_low: 1.5
            monst_anim_duration_high: 2.5
        Monster:
            id: monster2_image_lvl8
            monst_anim_duration_low: 1.0
            monst_anim_duration_high: 1.5
        Character:
            id: character_image_lvl8

<Level9>:
    name: "level9"
    on_pre_enter: app.screen_on_pre_enter(9)
    on_pre_leave: app.screen_on_pre_leave(9)
    on_enter: app.screen_on_enter(9)
    FloatLayout:
        id: layout_lvl9
        on_touch_down: app.touch_down_handler(9, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl9.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl9
        LevelNumber
            id: level_number_lvl9
        RemainingLifePercent
            id: remaining_life_percent_lvl9
        Monster:
            id: monster1_image_lvl9
            monst_anim_duration_low: 2.5
            monst_anim_duration_high: 3.5
        Monster2:
            id: monster2_image_lvl9
            monst_anim_duration_low: 1.2
            monst_anim_duration_high: 1.7
        Character:
            id: character_image_lvl9

<Level10>:
    name: "level10"
    on_pre_enter: app.screen_on_pre_enter(10)
    on_pre_leave: app.screen_on_pre_leave(10)
    on_enter: app.screen_on_enter(10)
    FloatLayout:
        id: layout_lvl10
        on_touch_down: app.touch_down_handler(10, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl10.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl10
        LevelNumber
            id: level_number_lvl10
        RemainingLifePercent
            id: remaining_life_percent_lvl10
        Monster:
            id: monster1_image_lvl10
            monst_anim_duration_low: 1.5
            monst_anim_duration_high: 2.5
        Monster2:
            id: monster2_image_lvl10
            monst_anim_duration_low: 0.8
            monst_anim_duration_high: 1.2
        Monster2:
            id: monster3_image_lvl10
            monst_anim_duration_low: 1.0
            monst_anim_duration_high: 1.5
        Character:
            id: character_image_lvl10

<Level11>:
    name: "level11"
    on_pre_enter: app.screen_on_pre_enter(11)
    on_pre_leave: app.screen_on_pre_leave(11)
    on_enter: app.screen_on_enter(11)
    FloatLayout:
        id: layout_lvl11
        on_touch_down: app.touch_down_handler(11, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl11.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl11
        LevelNumber
            id: level_number_lvl11
        RemainingLifePercent
            id: remaining_life_percent_lvl11
        Fire:
            id: fire1_lvl11
            fire_start_pos_hint: {'x': 1.5, 'y': 0.5}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.5}
            fire_anim_duration: 3.5
        Monster:
            id: monster1_image_lvl11
            monst_anim_duration_low: 2.5
            monst_anim_duration_high: 3.5
        Monster2:
            id: monster2_image_lvl11
            monst_anim_duration_low: 2.0
            monst_anim_duration_high: 2.5
        Character:
            id: character_image_lvl11

<Level12>:
    name: "level12"
    on_pre_enter: app.screen_on_pre_enter(12)
    on_pre_leave: app.screen_on_pre_leave(12)
    on_enter: app.screen_on_enter(12)
    FloatLayout:
        id: layout_lvl12
        on_touch_down: app.touch_down_handler(12, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl12.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl12
        LevelNumber
            id: level_number_lvl12
        RemainingLifePercent
            id: remaining_life_percent_lvl12
        Fire:
            id: fire1_lvl12
            fire_start_pos_hint: {'x': 1.5, 'y': 0.5}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.5}
            fire_anim_duration: 2.5
        Monster:
            id: monster1_image_lvl12
            monst_anim_duration_low: 2.5
            monst_anim_duration_high: 3.5
        Monster2:
            id: monster2_image_lvl12
            monst_anim_duration_low: 1.5
            monst_anim_duration_high: 2.0
        Character:
            id: character_image_lvl12

<Level13>:
    name: "level13"
    on_pre_enter: app.screen_on_pre_enter(13)
    on_pre_leave: app.screen_on_pre_leave(13)
    on_enter: app.screen_on_enter(13)
    FloatLayout:
        id: layout_lvl13
        on_touch_down: app.touch_down_handler(13, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl13.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl13
        LevelNumber
            id: level_number_lvl13
        RemainingLifePercent
            id: remaining_life_percent_lvl13
        Fire:
            id: fire1_lvl13
            fire_start_pos_hint: {'x': 1.5, 'y': 0.5}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.5}
            fire_anim_duration: 2.5
        Fire:
            id: fire2_lvl13
            fire_start_pos_hint: {'x': 0.5, 'y': 1.5}
            fire_end_pos_hint: {'x': 0.5, 'y': -0.5}
            fire_anim_duration: 3.5
        Monster:
            id: monster1_image_lvl13
            monst_anim_duration_low: 2.5
            monst_anim_duration_high: 3.5
        Monster2:
            id: monster2_image_lvl13
            monst_anim_duration_low: 2.5
            monst_anim_duration_high: 3.0
        Character:
            id: character_image_lvl13

<Level14>:
    name: "level14"
    on_pre_enter: app.screen_on_pre_enter(14)
    on_pre_leave: app.screen_on_pre_leave(14)
    on_enter: app.screen_on_enter(14)
    FloatLayout:
        id: layout_lvl14
        on_touch_down: app.touch_down_handler(14, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl14.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl14
        LevelNumber
            id: level_number_lvl14
        RemainingLifePercent
            id: remaining_life_percent_lvl14
        Fire:
            id: fire1_lvl14
            fire_start_pos_hint: {'x': 1.5, 'y': 0.2}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.2}
            fire_anim_duration: 2.5
        Fire:
            id: fire2_lvl14
            fire_start_pos_hint: {'x': 1.5, 'y': 0.8}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.8}
            fire_anim_duration: 3.5
        Fire:
            id: fire3_lvl14
            fire_start_pos_hint: {'x': -1.5, 'y': 0.5}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.5}
            fire_anim_duration: 3.5
        Fire:
            id: fire4_lvl14
            fire_start_pos_hint: {'x': 0.8, 'y': 1.5}
            fire_end_pos_hint: {'x': 0.8, 'y': -0.5}
            fire_anim_duration: 2.5
        Fire:
            id: fire5_lvl14
            fire_start_pos_hint: {'x': 0.2, 'y': 1.5}
            fire_end_pos_hint: {'x': 0.2, 'y': -0.5}
            fire_anim_duration: 3.5
        Fire:
            id: fire6_lvl14
            fire_start_pos_hint: {'x': 0.5, 'y': 1.5}
            fire_end_pos_hint: {'x': 0.5, 'y': -0.5}
            fire_anim_duration: 2.5
        Character:
            id: character_image_lvl14

<Level15>:
    name: "level15"
    on_pre_enter: app.screen_on_pre_enter(15)
    on_pre_leave: app.screen_on_pre_leave(15)
    on_enter: app.screen_on_enter(15)
    FloatLayout:
        id: layout_lvl15
        on_touch_down: app.touch_down_handler(15, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl15.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl15
        LevelNumber
            id: level_number_lvl15
        RemainingLifePercent
            id: remaining_life_percent_lvl15
        Fire:
            id: fire1_lvl15
            fire_start_pos_hint: {'x': 1.2, 'y': 0.2}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.2}
            fire_anim_duration: 2.5
        Fire:
            id: fire2_lvl15
            fire_start_pos_hint: {'x': 1.5, 'y': 0.7}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.7}
            fire_anim_duration: 3.5
        Fire:
            id: fire3_lvl15
            fire_start_pos_hint: {'x': 0.5, 'y': 1.5}
            fire_end_pos_hint: {'x': 0.5, 'y': -0.5}
            fire_anim_duration: 2.5
        Monster2:
            id: monster1_image_lvl15
            monst_anim_duration_low: 3.0
            monst_anim_duration_high: 3.5
        Monster2:
            id: monster2_image_lvl15
            monst_anim_duration_low: 3.0
            monst_anim_duration_high: 3.5
        Character:
            id: character_image_lvl15

<Level16>:
    name: "level16"
    on_pre_enter: app.screen_on_pre_enter(16)
    on_pre_leave: app.screen_on_pre_leave(16)
    on_enter: app.screen_on_enter(16)
    FloatLayout:
        id: layout_lvl16
        on_touch_down: app.touch_down_handler(16, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl16.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl16
        LevelNumber
            id: level_number_lvl16
        RemainingLifePercent
            id: remaining_life_percent_lvl16
        Fire:
            id: fire1_lvl16
            fire_start_pos_hint: {'x': 1.5, 'y': 0.2}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.2}
            fire_anim_duration: 2.5
        Fire:
            id: fire2_lvl16
            fire_start_pos_hint: {'x': 1.5, 'y': 0.7}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.7}
            fire_anim_duration: 1.5
        Monster:
            id: monster1_image_lvl16
            monst_anim_duration_low: 2.0
            monst_anim_duration_high: 3.5
        Monster2:
            id: monster2_image_lvl16
            monst_anim_duration_low: 3.0
            monst_anim_duration_high: 3.5
        Monster2:
            id: monster3_image_lvl16
            monst_anim_duration_low: 1.0
            monst_anim_duration_high: 1.5
        Character:
            id: character_image_lvl16

<Level17>:
    name: "level17"
    on_pre_enter: app.screen_on_pre_enter(17)
    on_pre_leave: app.screen_on_pre_leave(17)
    on_enter: app.screen_on_enter(17)
    FloatLayout:
        id: layout_lvl17
        on_touch_down: app.touch_down_handler(17, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl17.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl17
        LevelNumber
            id: level_number_lvl17
        RemainingLifePercent
            id: remaining_life_percent_lvl17
        Fire:
            id: fire1_lvl17
            fire_start_pos_hint: {'x': 1.5, 'y': 0.3}
            fire_end_pos_hint: {'x': -1.5, 'y': 0.3}
            fire_anim_duration: 1.5
        Fire:
            id: fire2_lvl17
            fire_start_pos_hint: {'x': 1.5, 'y': 0.8}
            fire_end_pos_hint: {'x': -1.5, 'y': 0.8}
            fire_anim_duration: 1.0
        Fire:
            id: fire3_lvl17
            fire_start_pos_hint: {'x': 0.8, 'y': -1.5}
            fire_end_pos_hint: {'x': 0.8, 'y': 1.5}
            fire_anim_duration: 1.5
        Fire:
            id: fire4_lvl17
            fire_start_pos_hint: {'x': 0.3, 'y': 1.5}
            fire_end_pos_hint: {'x': 0.3, 'y': -1.5}
            fire_anim_duration: 1.0
        Character:
            id: character_image_lvl17

<Level18>:
    name: "level18"
    on_pre_enter: app.screen_on_pre_enter(18)
    on_pre_leave: app.screen_on_pre_leave(18)
    on_enter: app.screen_on_enter(18)
    FloatLayout:
        id: layout_lvl18
        on_touch_down: app.touch_down_handler(18, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl18.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl18
        LevelNumber
            id: level_number_lvl18
        RemainingLifePercent
            id: remaining_life_percent_lvl18
        Fire:
            id: fire1_lvl18
            fire_start_pos_hint: {'x': 0.8, 'y': 0.3}
            fire_end_pos_hint: {'x': 0.2, 'y': 0.3}
            fire_anim_duration: 1.2
        Fire:
            id: fire2_lvl18
            fire_start_pos_hint: {'x': 0.3, 'y': 0.8}
            fire_end_pos_hint: {'x': 0.7, 'y': 0.8}
            fire_anim_duration: 1.3
        Fire:
            id: fire3_lvl18
            fire_start_pos_hint: {'x': 0.8, 'y': 0.3}
            fire_end_pos_hint: {'x': 0.8, 'y': 0.7}
            fire_anim_duration: 1.2
        Fire:
            id: fire4_lvl18
            fire_start_pos_hint: {'x': 0.3, 'y': 0.8}
            fire_end_pos_hint: {'x': 0.3, 'y': 0.2}
            fire_anim_duration: 1.0
        Monster:
            id: monster1_image_lvl18
            monst_anim_duration_low: 1.0
            monst_anim_duration_high: 1.6
        Monster2:
            id: monster2_image_lvl18
            monst_anim_duration_low: 1.0
            monst_anim_duration_high: 2.0
        Monster2:
            id: monster3_image_lvl18
            monst_anim_duration_low: 1.0
            monst_anim_duration_high: 1.2
        Character:
            id: character_image_lvl18

<Level19>:
    name: "level19"
    on_pre_enter: app.screen_on_pre_enter(19)
    on_pre_leave: app.screen_on_pre_leave(19)
    on_enter: app.screen_on_enter(19)
    FloatLayout:
        id: layout_lvl19
        on_touch_down: app.touch_down_handler(19, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl19.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl19
        LevelNumber
            id: level_number_lvl19
        RemainingLifePercent
            id: remaining_life_percent_lvl19
        Fire:
            id: fire1_lvl19
            fire_start_pos_hint: {'x': 0.8, 'y': 0.3}
            fire_end_pos_hint: {'x': 0.2, 'y': 0.3}
            fire_anim_duration: 1.2
        Fire:
            id: fire2_lvl19
            fire_start_pos_hint: {'x': 0.3, 'y': 0.8}
            fire_end_pos_hint: {'x': 0.7, 'y': 0.8}
            fire_anim_duration: 1.0
        Fire:
            id: fire3_lvl19
            fire_start_pos_hint: {'x': -1.5, 'y': 0.5}
            fire_end_pos_hint: {'x': 1.5, 'y': 0.5}
            fire_anim_duration: 1.5
        Fire:
            id: fire4_lvl19
            fire_start_pos_hint: {'x': 0.8, 'y': 0.3}
            fire_end_pos_hint: {'x': 0.8, 'y': 0.7}
            fire_anim_duration: 1.2
        Fire:
            id: fire5_lvl19
            fire_start_pos_hint: {'x': 0.3, 'y': 0.8}
            fire_end_pos_hint: {'x': 0.3, 'y': 0.2}
            fire_anim_duration: 1.3
        Fire:
            id: fire6_lvl19
            fire_start_pos_hint: {'x': 0.5, 'y': -1.5}
            fire_end_pos_hint: {'x': 0.5, 'y': 1.5}
            fire_anim_duration: 1.4
        Character:
            id: character_image_lvl19

<Level20>:
    name: "level20"
    on_pre_enter: app.screen_on_pre_enter(20)
    on_pre_leave: app.screen_on_pre_leave(20)
    on_enter: app.screen_on_enter(20)
    FloatLayout:
        id: layout_lvl20
        on_touch_down: app.touch_down_handler(20, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl20.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl20
        LevelNumber
            id: level_number_lvl20
        RemainingLifePercent
            id: remaining_life_percent_lvl20
        Fire:
            id: fire1_lvl20
            fire_start_pos_hint: {'x': 0.8, 'y': 0.3}
            fire_end_pos_hint: {'x': 0.2, 'y': 0.3}
            fire_anim_duration: 1.5
        Fire:
            id: fire2_lvl20
            fire_start_pos_hint: {'x': 0.3, 'y': 0.8}
            fire_end_pos_hint: {'x': 0.7, 'y': 0.8}
            fire_anim_duration: 1.3
        Fire:
            id: fire3_lvl20
            fire_start_pos_hint: {'x': -1.5, 'y': 0.5}
            fire_end_pos_hint: {'x': 1.5, 'y': 0.5}
            fire_anim_duration: 1.6
        Fire:
            id: fire4_lvl20
            fire_start_pos_hint: {'x': 0.1, 'y': 0.3}
            fire_end_pos_hint: {'x': 0.9, 'y': 0.3}
            fire_anim_duration: 1.5
        Fire:
            id: fire5_lvl20
            fire_start_pos_hint: {'x': 0.8, 'y': 0.3}
            fire_end_pos_hint: {'x': 0.8, 'y': 0.7}
            fire_anim_duration: 1.5
        Fire:
            id: fire6_lvl20
            fire_start_pos_hint: {'x': 0.3, 'y': 0.8}
            fire_end_pos_hint: {'x': 0.3, 'y': 0.2}
            fire_anim_duration: 1.3
        Fire:
            id: fire7_lvl20
            fire_start_pos_hint: {'x': 0.5, 'y': -1.5}
            fire_end_pos_hint: {'x': 0.5, 'y': 1.5}
            fire_anim_duration: 1.6
        Fire:
            id: fire8_lvl20
            fire_start_pos_hint: {'x': 0.5, 'y': 0.1}
            fire_end_pos_hint: {'x': 0.5, 'y': 0.9}
            fire_anim_duration: 1.3
        Character:
            id: character_image_lvl20

<Level21>:
    name: "level21"
    on_pre_enter: app.screen_on_pre_enter(21)
    on_pre_leave: app.screen_on_pre_leave(21)
    on_enter: app.screen_on_enter(21)
    FloatLayout:
        id: layout_lvl21
        on_touch_down: app.touch_down_handler(21, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl1.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl21
        LevelNumber
            id: level_number_lvl21
        RemainingLifePercent
            id: remaining_life_percent_lvl21
        Fire:
            id: fire1_lvl21
            fire_start_pos_hint: {'x': 0.8, 'y': 0.3}
            fire_end_pos_hint: {'x': 0.2, 'y': 0.3}
            fire_anim_duration: 1.8
        Fire:
            id: fire2_lvl21
            fire_start_pos_hint: {'x': 0.3, 'y': 0.8}
            fire_end_pos_hint: {'x': 0.7, 'y': 0.8}
            fire_anim_duration: 1.5
        Fire:
            id: fire3_lvl21
            fire_start_pos_hint: {'x': -1.5, 'y': 0.5}
            fire_end_pos_hint: {'x': 1.5, 'y': 0.5}
            fire_anim_duration: 2.0
        Fire:
            id: fire4_lvl21
            fire_start_pos_hint: {'x': 0.1, 'y': 0.3}
            fire_end_pos_hint: {'x': 0.9, 'y': 0.3}
            fire_anim_duration: 2.5
        Monster:
            id: monster1_image_lvl21
            monst_anim_duration_low: 1.0
            monst_anim_duration_high: 1.3
        Monster2:
            id: monster2_image_lvl21
            monst_anim_duration_low: 1.0
            monst_anim_duration_high: 1.5
        Character:
            id: character_image_lvl21

<Level22>:
    name: "level22"
    on_pre_enter: app.screen_on_pre_enter(22)
    on_pre_leave: app.screen_on_pre_leave(22)
    on_enter: app.screen_on_enter(22)
    FloatLayout:
        id: layout_lvl22
        on_touch_down: app.touch_down_handler(22, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl2.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl22
        LevelNumber
            id: level_number_lvl22
        RemainingLifePercent
            id: remaining_life_percent_lvl22
        Fire:
            id: fire1_lvl22
            fire_start_pos_hint: {'x': 0.8, 'y': 0.3}
            fire_end_pos_hint: {'x': 0.2, 'y': 0.3}
            fire_anim_duration: 1.9
        Fire:
            id: fire2_lvl22
            fire_start_pos_hint: {'x': 0.3, 'y': 0.8}
            fire_end_pos_hint: {'x': 0.7, 'y': 0.8}
            fire_anim_duration: 2.0
        Fire:
            id: fire3_lvl22
            fire_start_pos_hint: {'x': -1.5, 'y': 0.5}
            fire_end_pos_hint: {'x': 1.5, 'y': 0.5}
            fire_anim_duration: 2.0
        Fire:
            id: fire4_lvl22
            fire_start_pos_hint: {'x': 0.1, 'y': 0.3}
            fire_end_pos_hint: {'x': 0.9, 'y': 0.3}
            fire_anim_duration: 2.5
        Monster:
            id: monster1_image_lvl22
            monst_anim_duration_low: 1.0
            monst_anim_duration_high: 1.8
        Monster2:
            id: monster2_image_lvl22
            monst_anim_duration_low: 1.0
            monst_anim_duration_high: 2.0
        Character:
            id: character_image_lvl22

<Level23>:
    name: "level23"
    on_pre_enter: app.screen_on_pre_enter(23)
    on_pre_leave: app.screen_on_pre_leave(23)
    on_enter: app.screen_on_enter(23)
    FloatLayout:
        id: layout_lvl23
        on_touch_down: app.touch_down_handler(23, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl3.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl23
        LevelNumber
            id: level_number_lvl23
        RemainingLifePercent
            id: remaining_life_percent_lvl23
        Fire:
            id: fire1_lvl23
            fire_start_pos_hint: {'x': -1.5, 'y': 0.3}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.3}
            fire_anim_duration: 1.8
        Fire:
            id: fire2_lvl23
            fire_start_pos_hint: {'x': -1.5, 'y': 0.8}
            fire_end_pos_hint: {'x': -0.5, 'y': 0.8}
            fire_anim_duration: 2.0
        Monster:
            id: monster1_image_lvl23
            monst_anim_duration_low: 1.5
            monst_anim_duration_high: 2.0
        Monster2:
            id: monster2_image_lvl23
            monst_anim_duration_low: 1.5
            monst_anim_duration_high: 2.5
        Character:
            id: character_image_lvl23

<Level24>:
    name: "level24"
    on_pre_enter: app.screen_on_pre_enter(24)
    on_pre_leave: app.screen_on_pre_leave(24)
    on_enter: app.screen_on_enter(24)
    FloatLayout:
        id: layout_lvl24
        on_touch_down: app.touch_down_handler(24, args)
        canvas.before:
            Rectangle:
                pos: self.pos
                size: self.size
                source: "images/levels-bg/bg_lvl4.jpg"
        NumCollectedCoins:
            id: num_coins_collected_lvl24
        LevelNumber
            id: level_number_lvl24
        RemainingLifePercent
            id: remaining_life_percent_lvl24
        Fire:
            id: fire1_lvl24
            fire_start_pos_hint: {'x': 0.8, 'y': 0.3}
            fire_end_pos_hint: {'x': 0.2, 'y': 0.3}
            fire_anim_duration: 1.8
        Fire:
            id: fire2_lvl24
            fire_start_pos_hint: {'x': 0.3, 'y': 0.8}
            fire_end_pos_hint: {'x': 0.7, 'y': 0.8}
            fire_anim_duration: 1.5
        Monster:
            id: monster1_image_lvl24
            monst_anim_duration_low: 1.5
            monst_anim_duration_high: 1.7
        Monster2:
            id: monster2_image_lvl24
            monst_anim_duration_low: 1.8
            monst_anim_duration_high: 2.5
        Monster:
            id: monster3_image_lvl24
            monst_anim_duration_low: 1.5
            monst_anim_duration_high: 2.0
        Character:
            id: character_image_lvl24

<NumCollectedCoins@Label>:
    size_hint: (0.1, 0.02)
    pos_hint: {'x': 0.026, 'y': 0.97}
    text: "Coins 0"
    font_size: 20

<LevelNumber@Label>:
    size_hint: (0.1, 0.02)
    pos_hint: {'x': 0.15, 'y': 0.97}
    text: "Level"
    font_size: 20

<RemainingLifePercent@Label>:
    remaining_life_size_hint_x: 0.2
    size_hint: (0.2, 0.022)
    pos_hint: {'x': 0.3, 'y': 0.97}
    font_size: 20
    canvas:
        Color:
            rgb: (1, 0, 0)
        Rectangle:
            pos: self.pos
            size: self.size

<Monster@Image>:
    size_hint: (0.15, 0.15)
    pos_hint: {'x': 0.8, 'y': 0.8}
    source: "images/10.png"
    im_num: 10
    start_im_num: 10
    end_im_num: 17
    allow_stretch: True
    on_im_num: app.change_monst_im(self)
    on_pos_hint: app.monst_pos_hint(self)

<Monster2@Image>:
    size_hint: (0.15, 0.15)
    pos_hint: {'x': 0.8, 'y': 0.8}
    source: "images/21.png"
    im_num: 21
    start_im_num: 21
    end_im_num: 29
    allow_stretch: True
    on_im_num: app.change_monst_im(self)
    on_pos_hint: app.monst_pos_hint(self)

<Character@Image>:
    size_hint: (0.15, 0.15)
    pos_hint: {'x': 0.0, 'y': 0.0}
    source: "images/0.png"
    im_num: 0
    start_im_num: 0
    end_im_num: 7
    dead_start_im_num: 91
    dead_end_im_num: 95
    allow_stretch: True
    on_im_num: app.change_char_im(self)
    on_pos_hint: app.char_pos_hint(self)

<Fire@Label>:
    pos_hint: {'x': 1.1, 'y': 1.1}
    on_pos_hint: app.fire_pos_hint(self)
    size_hint: (0.03, 0.03)
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size
            source: "fire.png"

<ImageButton>:
    canvas.before:
        Color:
            rgba: (0.6, 0.6, 0.6, 0.5)
        Rectangle:
            pos: self.pos
            size: self.size

